name: iso_duration_parser
description: A package which parses ISO 8061 Duration (PnYnMnDTnHnMnS format).
homepage: https://github.com/mzdm/iso_duration_parser
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
